DELETE TABLE IF EXISTS eban_pr;

CREATE TABLE IF NOT EXISTS eban_pr
(
    BANFN INT IDENTIY PRIMARY KEY, 
    BNFPO INT, 
    TXZ01 NVARCHAR(400), 
    MATNR INT, 
    MENGE INT, 
    MEINS NVARCHAR(100), 
    BADAT DATE, 
    FKBER NVARCHAR(100), 
    BANPR BOOLEAN
);